name: flutter_shop
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

# 上线需要的第三方库，放在dependencies里
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^2.0.7
  flutter_swiper : ^1.1.6
  flutter_screenutil : ^0.7.0
  url_launcher: ^5.0.1
  flutter_easyrefresh: ^2.0.8

# 上线不需要，只是测试阶段需要的第三方库，放在dev_dependencies里，这样上线打包不会打包进去
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - data/homePage.json
  - data/category.json

  - image/home_swiper1.jpg
  - image/home_swiper2.jpg
  - image/home_swiper3.jpg
  - image/home_swiper4.jpg
  - image/home_swiper5.jpg
  - image/home_swiper6.jpg

  - image/top_navigator1.jpg
  - image/top_navigator2.jpg
  - image/top_navigator3.jpg
  - image/top_navigator4.jpg
  - image/top_navigator5.jpg
  - image/top_navigator6.jpg
  - image/top_navigator7.jpg
  - image/top_navigator8.jpg
  - image/top_navigator9.jpg
  - image/top_navigator10.jpg
  
  - image/adBanner1.jpg
  - image/adTell.jpg

  - image/recommend1.jpg
  - image/recommend2.jpg
  - image/recommend3.jpg
  - image/recommend4.jpg
  - image/recommend5.jpg
  - image/recommend6.jpg
  - image/recommend7.jpg

  - image/floor1.jpg
  - image/floor2.jpg
  - image/floor3.jpg
  - image/floor4.jpg
  - image/floor5.jpg
  - image/floor6.jpg

  - image/hotGoods1.jpg
  - image/hotGoods2.jpg
  - image/hotGoods3.jpg
  - image/hotGoods4.jpg
  - image/hotGoods5.jpg
  - image/hotGoods6.jpg
  - image/hotGoods7.jpg
  - image/hotGoods8.jpg
  - image/hotGoods9.jpg
  - image/hotGoods10.jpg
  - image/hotGoods11.jpg
  - image/hotGoods12.jpg
  - image/hotGoods13.jpg
  - image/hotGoods14.jpg
  - image/hotGoods15.jpg
  - image/hotGoods16.jpg

  

  
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
