name: flutter_shop
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

# 上线需要的第三方库，放在dependencies里
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^2.0.7
  flutter_swiper : ^1.1.6
  flutter_screenutil : ^0.7.0
  url_launcher: ^5.0.1
  flutter_easyrefresh: ^2.0.8
  provide: ^1.0.2  #状态管理组件，谷歌出品
  fluro: "^1.5.1" #Flutter本身提供了路由机制，作个人的小型项目，完全足够了。但是如果你要作企业级开发，可能就会把入口文件变得臃肿不堪。而再Flutter问世之初，就已经了企业级路由方案fluro。
  shared_preferences: ^0.5.1 #购物车中的一项功能是持久化，就是我们关掉APP，下次进入后，还是可以显示出我们放入购物车的商品。但是这些商品不和后台进行数据交互，前台如果使用sqflite又显得太重，还要懂SQL知识。所以在购物车页面我们采用shared_preferences来进行持久化，它是简单的键-值的操作。shared_preferences是一个Flutter官方出的插件，它的主要作用就是可以key-value的形式来进行APP可客户端的持久化。

# 上线不需要，只是测试阶段需要的第三方库，放在dev_dependencies里，这样上线打包不会打包进去
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - data/homePage.json
  - data/category.json
  - data/goodsDateils.json
  - data/goodsDateilsOther.json

  - image/home_swiper1.jpg
  - image/home_swiper2.jpg
  - image/home_swiper3.jpg
  - image/home_swiper4.jpg
  - image/home_swiper5.jpg
  - image/home_swiper6.jpg

  - image/top_navigator1.jpg
  - image/top_navigator2.jpg
  - image/top_navigator3.jpg
  - image/top_navigator4.jpg
  - image/top_navigator5.jpg
  - image/top_navigator6.jpg
  - image/top_navigator7.jpg
  - image/top_navigator8.jpg
  - image/top_navigator9.jpg
  - image/top_navigator10.jpg
  
  - image/adBanner1.jpg
  - image/adTell.jpg

  - image/recommend1.jpg
  - image/recommend2.jpg
  - image/recommend3.jpg
  - image/recommend4.jpg
  - image/recommend5.jpg
  - image/recommend6.jpg
  - image/recommend7.jpg

  - image/floor1.jpg
  - image/floor2.jpg
  - image/floor3.jpg
  - image/floor4.jpg
  - image/floor5.jpg
  - image/floor6.jpg

  - image/hotGoods1.jpg
  - image/hotGoods2.jpg
  - image/hotGoods3.jpg
  - image/hotGoods4.jpg
  - image/hotGoods5.jpg
  - image/hotGoods6.jpg
  - image/hotGoods7.jpg
  - image/hotGoods8.jpg
  - image/hotGoods9.jpg
  - image/hotGoods10.jpg
  - image/hotGoods11.jpg
  - image/hotGoods12.jpg
  - image/hotGoods13.jpg
  - image/hotGoods14.jpg
  - image/hotGoods15.jpg
  - image/hotGoods16.jpg

  - image/category/man/man1.jpg
  - image/category/man/man2.jpg
  - image/category/man/man3.jpg
  - image/category/man/man4.jpg
  - image/category/man/man5.jpg
  - image/category/man/man6.jpg
  - image/category/man/man7.jpg
  - image/category/man/man8.jpg
  - image/category/man/man9.jpg
  - image/category/man/man10.jpg
  - image/category/man/man11.jpg
  - image/category/man/man12.jpg
  - image/category/man/man13.jpg
  - image/category/man/man14.jpg
  - image/category/man/man15.jpg
  - image/category/man/man16.jpg
  - image/category/man/man17.jpg
  - image/category/man/man18.jpg
  - image/category/man/man19.png
  - image/category/man/man20.jpg
  - image/category/man/man21.jpg
  - image/category/man/man22.jpg
  - image/category/man/man23.jpg
  - image/category/man/man24.jpg
  - image/category/man/man25.jpg
  - image/category/man/man26.jpg
  - image/category/man/man27.jpg

  - image/category/woman/woman1.jpg
  - image/category/woman/woman2.jpg
  - image/category/woman/woman3.jpg
  - image/category/woman/woman4.jpg
  - image/category/woman/woman5.jpg
  - image/category/woman/woman6.jpg
  - image/category/woman/woman7.jpg
  - image/category/woman/woman8.jpg
  - image/category/woman/woman9.jpg
  - image/category/woman/woman10.jpg
  - image/category/woman/woman11.jpg
  - image/category/woman/woman12.jpg
  - image/category/woman/woman13.jpg
  - image/category/woman/woman14.jpg
  - image/category/woman/woman15.jpg
  - image/category/woman/woman16.jpg
  - image/category/woman/woman17.jpg
  - image/category/woman/woman18.jpg
  - image/category/woman/woman19.jpg
  - image/category/woman/woman20.jpg
  - image/category/woman/woman21.jpg
  - image/category/woman/woman22.jpg
  - image/category/woman/woman23.jpg
  - image/category/woman/woman24.jpg
  - image/category/woman/woman25.jpg
  - image/category/woman/woman26.jpg
  - image/category/woman/woman27.jpg

  - image/goods_details/goods_details1.jpg
  - image/goods_details/goods_details2.jpg
  - image/goods_details/goods_details3.jpg
  - image/goods_details/goods_details4.jpg
  - image/goods_details/goods_details5.jpg
  - image/goods_details/goods_details6.jpg
  - image/goods_details/goods_details7.jpg
  - image/goods_details/goods_details8.jpg
  - image/goods_details/goods_details9.jpg
  - image/goods_details/goods_details10.jpg
  - image/goods_details/goods_details11.jpg
  - image/goods_details/goods_details12.jpg
  - image/goods_details/goods_details13.jpg
  - image/goods_details/goods_details14.jpg
  - image/goods_details/goods_details15.jpg
  - image/goods_details/goods_details16.jpg
  - image/goods_details/goods_details17.jpg
  - image/goods_details/goods_details18.jpg
  - image/goods_details/goods_details19.jpg
  - image/goods_details/goods_details20.jpg
  - image/goods_details/goods_details21.jpg
  - image/goods_details/goods_details22.jpg
  - image/goods_details/goods_details23.jpg
  - image/goods_details/goods_details24.jpg
  - image/goods_details/goods_details25.jpg

  - image/goods_details/another/img1.jpg
  - image/goods_details/another/img2.jpg
  - image/goods_details/another/img3.jpg
  - image/goods_details/another/img4.jpg
  - image/goods_details/another/img5.jpg
  - image/goods_details/another/img6.jpg
  - image/goods_details/another/img7.jpg
  - image/goods_details/another/img8.jpg
   

  - image/goods_details/comment/comment1.jpg
  - image/goods_details/comment/comment2.jpg
  - image/goods_details/comment/comment3.jpg
  - image/goods_details/comment/comment4.jpg
  - image/goods_details/comment/comment5.jpg
  - image/goods_details/comment/comment6.jpg
  - image/goods_details/comment/comment7.jpg
  - image/goods_details/comment/comment8.jpg
  - image/goods_details/comment/comment9.jpg
  
  - image/admin_img.jpg

  - image/merber/guanggao.png
  - image/merber/shouye.png
  - image/merber/xiaoxi.png
  - image/merber/shoucang.png
  - image/merber/guanzhu.png
  - image/merber/zuji.png
  - image/merber/daifu.jpg
  - image/merber/daifa.jpg
  - image/merber/daishou.jpg
  - image/merber/pingjia.jpg
  - image/merber/shouhou.jpg

  - image/merber/qiandao.jpg
  - image/merber/huanbao.jpg
  - image/merber/kefu.jpg
  - image/merber/daren.jpg
  - image/merber/shouhuo.jpg

  
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
